name: Prettier

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # Use the same version as `format`
      - uses: creyD/prettier_action@6602189cf8bac1ce73ffe601925f6127ab7f21ac
        with:
          dry: True
          prettier_options: --check **/*.{md,yaml}
      - if: failure()
        name: format
        # Pin to a specific commit to reduce the risk of token leaks by other versions.
        # creyD/prettier_action@v4.2 (6602189cf8bac1ce73ffe601925f6127ab7f21ac)
        uses: creyD/prettier_action@6602189cf8bac1ce73ffe601925f6127ab7f21ac
        with:
          prettier_options: --write **/*.{md,yaml}
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
